theme: jekyll-theme-tactile
title: W çš„åšå®¢111
description: æ¥ç©å‘€ğŸ˜œ
lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
